//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attore
    {
        public long Id { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public Nullable<System.DateTime> DataNascita { get; set; }
        public string CittaNascita { get; set; }
        public string StatoNascita { get; set; }
        public string CapNascita { get; set; }
        public string CittaResidenza { get; set; }
        public string ViaResidenza { get; set; }
        public string CivicoResidenza { get; set; }
        public string CapResidenza { get; set; }
        public string CF { get; set; }
        public string DocumentoTipo { get; set; }
        public string DocumentoNumero { get; set; }
        public string Ruolo { get; set; }
    }
}
