//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avvocato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avvocato()
        {
            this.Verbale = new HashSet<Verbale>();
        }
    
        public long Id { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string IndirizzoStudio { get; set; }
        public string TelefonoStudio { get; set; }
        public string FaxStudio { get; set; }
        public string Cellulare { get; set; }
        public string Email { get; set; }
        public string Foro { get; set; }
        public string CittaStudio { get; set; }
        public Nullable<bool> Assegnato { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Verbale> Verbale { get; set; }
    }
}
