//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comando
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComandoEntities : DbContext
    {
        public ComandoEntities()
            : base("name=ComandoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agente> Agente { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<Attore> Attore { get; set; }
        public virtual DbSet<Avvocato> Avvocato { get; set; }
        public virtual DbSet<CategoriaVerbale> CategoriaVerbale { get; set; }
        public virtual DbSet<Comuni> Comuni { get; set; }
        public virtual DbSet<Custode> Custode { get; set; }
        public virtual DbSet<documenti_categorie> documenti_categorie { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<DocumentoCollegato> DocumentoCollegato { get; set; }
        public virtual DbSet<DocumentoWord> DocumentoWord { get; set; }
        public virtual DbSet<ListaComuni> ListaComuni { get; set; }
        public virtual DbSet<Memberships> Memberships { get; set; }
        public virtual DbSet<Patente> Patente { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<Proprietario> Proprietario { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<Regioni> Regioni { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Stati> Stati { get; set; }
        public virtual DbSet<TipologiaAnagrafica> TipologiaAnagrafica { get; set; }
        public virtual DbSet<TipoVeicolo> TipoVeicolo { get; set; }
        public virtual DbSet<Trasgressore> Trasgressore { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersOpenAuthAccounts> UsersOpenAuthAccounts { get; set; }
        public virtual DbSet<UsersOpenAuthData> UsersOpenAuthData { get; set; }
        public virtual DbSet<Utente> Utente { get; set; }
        public virtual DbSet<Veicolo> Veicolo { get; set; }
        public virtual DbSet<Verbale> Verbale { get; set; }
        public virtual DbSet<VerbaleElezioneDomicilio> VerbaleElezioneDomicilio { get; set; }
        public virtual DbSet<Violazione> Violazione { get; set; }
    }
}
