//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuni
    {
        public int Id { get; set; }
        public string nome { get; set; }
        public int idprovincia { get; set; }
        public int idregione { get; set; }
        public string catasto { get; set; }
    }
}
