//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuni
    {
        public string Istat { get; set; }
        public string Comune { get; set; }
        public string Provincia { get; set; }
        public string Regione { get; set; }
        public string Prefisso { get; set; }
        public string CAP { get; set; }
        public string CodFisco { get; set; }
        public string Abitanti { get; set; }
        public string Link { get; set; }
    }
}
