//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoWord
    {
        public long Id { get; set; }
        public string Path { get; set; }
        public string Titolo { get; set; }
        public Nullable<long> Verbale_Id { get; set; }
        public Nullable<long> Categoria { get; set; }
    
        public virtual VerbaleElezioneDomicilio VerbaleElezioneDomicilio { get; set; }
    }
}
