//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public long ID { get; set; }
        public string Descrizione { get; set; }
        public string Titolo { get; set; }
        public string Numero { get; set; }
    }
}
