//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patente
    {
        public long Id { get; set; }
        public string Categoria { get; set; }
        public string Numero { get; set; }
        public string RilasciataDa { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<long> Intestatario_Id { get; set; }
    
        public virtual Trasgressore Trasgressore { get; set; }
    }
}
