//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proprietario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proprietario()
        {
            this.Veicolo = new HashSet<Veicolo>();
        }
    
        public long Id { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string CittaNascita { get; set; }
        public Nullable<System.DateTime> DataNascita { get; set; }
        public string CittaResidenza { get; set; }
        public string IndirizzoResidenza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Veicolo> Veicolo { get; set; }
    }
}
