//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public int idprovincia { get; set; }
        public string nomeprovincia { get; set; }
        public int idregione { get; set; }
        public string siglaprovincia { get; set; }
    }
}
