//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stati
    {
        public string Codice2 { get; set; }
        public string Codice3 { get; set; }
        public long Id { get; set; }
        public string Nome { get; set; }
        public string NomeOriginale { get; set; }
        public string Sigla { get; set; }
    }
}
