//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trasgressore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trasgressore()
        {
            this.Verbale = new HashSet<Verbale>();
        }
    
        public long Id { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public Nullable<System.DateTime> DataNascita { get; set; }
        public string CittaNascita { get; set; }
        public string StatoNascita { get; set; }
        public string CapNascita { get; set; }
        public string CittaResidenza { get; set; }
        public string ViaResidenza { get; set; }
        public string CivicoResidenza { get; set; }
        public string CapResidenza { get; set; }
        public string CF { get; set; }
        public string Sesso { get; set; }
        public string CIttaDomicilio { get; set; }
        public string IndirizzoDomicilio { get; set; }
        public Nullable<long> PatenteId { get; set; }
    
        public virtual Patente Patente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Verbale> Verbale { get; set; }
    }
}
