//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veicolo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veicolo()
        {
            this.Verbale = new HashSet<Verbale>();
        }
    
        public long Id { get; set; }
        public string marca { get; set; }
        public string modello { get; set; }
        public string targa { get; set; }
        public string telaio { get; set; }
        public string colore { get; set; }
        public int TipoVeicolo_Id { get; set; }
        public string Nome { get; set; }
        public Nullable<long> Id_Proprietario { get; set; }
        public Nullable<long> Id_Custode { get; set; }
    
        public virtual Custode Custode { get; set; }
        public virtual TipoVeicolo TipoVeicolo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Verbale> Verbale { get; set; }
        public virtual Proprietario Proprietario { get; set; }
    }
}
