//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violazione
    {
        public long Id { get; set; }
        public string Nome { get; set; }
        public string Descrizione { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Articolo { get; set; }
        public string Indirizzo { get; set; }
        public string Citta { get; set; }
        public Nullable<long> Verbale_Id { get; set; }
    
        public virtual Verbale Verbale { get; set; }
    }
}
